'use strict';
// Native Chrome integration check for the new presentation, isolated from the user's browser.
const {spawn}=require('child_process'), http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),WebSocket=require('ws'),assert=require('assert/strict');
const url=process.argv[2]||'http://127.0.0.1:3000/badminton/r/QUALITY?gfx=medium';
const benchmarkOnly=process.argv.includes('--benchmark');
const footstepsOnly=process.argv.includes('--footsteps');
const port=9351, wait=ms=>new Promise(r=>setTimeout(r,ms));
const output=path.join(os.tmpdir(),'obm-presentation-review');fs.mkdirSync(output,{recursive:true});
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'obm-presentation-browser-'));
const exe=[process.env.CHROME,'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe','C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'].filter(Boolean).find(fs.existsSync);
if(!exe)throw new Error('Chrome or Edge required');
const proc=spawn(exe,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--disable-extensions','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required','--window-size=1440,900','about:blank'],{stdio:'ignore',windowsHide:true});
const json=p=>new Promise((resolve,reject)=>{const req=http.get({host:'127.0.0.1',port,path:p},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{try{resolve(JSON.parse(s));}catch(e){reject(e);}});});req.on('error',reject);req.setTimeout(2000,()=>req.destroy());});
let ws,seq=0;const pending=new Map(),logs=[],requests=[],downloads=[];
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,[resolve,reject]);ws.send(JSON.stringify({id,method,params}));});
async function ev(expression){const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function until(expression,ms=45000){const start=Date.now();while(Date.now()-start<ms){if(await ev(expression).catch(()=>false))return;await wait(250);}throw new Error('Timed out: '+expression);}
async function shot(name){const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(output,name),Buffer.from(r.data,'base64'));}
(async()=>{
try{
 let targets;for(let i=0;i<60&&!targets;i++){try{targets=await json('/json/list');}catch{}if(!targets)await wait(250);}
 const target=targets?.find(t=>t.type==='page');assert.ok(target,'debug browser page starts');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});
 ws.on('message',data=>{const m=JSON.parse(data);if(m.id&&pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(new Error(m.error.message)):r(m.result);}else if(m.method==='Runtime.exceptionThrown')logs.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);else if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')logs.push(m.params.entry.text);else if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')logs.push(m.params.args.map(a=>a.value||a.description).join(' '));else if(m.method==='Network.requestWillBeSent')requests.push({url:m.params.request.url,type:m.params.type});else if(m.method==='Browser.downloadWillBegin'||m.method==='Page.downloadWillBegin')downloads.push(m.params.url);});
 await send('Runtime.enable');await send('Page.enable');await send('Log.enable');
 await send('Network.enable');await send('Browser.setDownloadBehavior',{behavior:'deny',eventsEnabled:true});
 await send('Page.addScriptToEvaluateOnNewDocument',{source:"{const raf=requestAnimationFrame.bind(window);window.__frameSamples=[];window.requestAnimationFrame=cb=>raf(t=>{const at=performance.now();cb(t);if(window.__measureFrames&&__frameSamples.length<600)__frameSamples.push(performance.now()-at);});}"});
 await send('Page.addScriptToEvaluateOnNewDocument',{source:"localStorage.setItem('obm_name','Quality');localStorage.setItem('obm_ctrl','keyboard');localStorage.removeItem('obm_mute');"});
 await send('Page.addScriptToEvaluateOnNewDocument',{source:"window.__loopedAudioSources=0;const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){if(this.loop)window.__loopedAudioSources++;return start.apply(this,args);};"});
 await send('Page.navigate',{url});await until('!!(window.__ob?.R()&&window.__ob.state()?.p)');await wait(1000);
 const info=await ev(`({tier:__ob.tier(),heat:__ob.state().ht,stats:__ob.stats(),scene:__ob.R().debugScene()})`);console.log('Boot',JSON.stringify(info));
 await until('__ob.state().rp === "match"');
 if(benchmarkOnly){
  await wait(3000);
  await ev(`(()=>{const r=__ob.r3d().renderer,gl=r.getContext(),ext=gl.getExtension('EXT_disjoint_timer_query_webgl2'),original=r.render.bind(r),pending=[];window.__gpuSamples=[];window.__stopGpuProbe=()=>{r.render=original;pending.forEach(q=>gl.deleteQuery(q));};if(ext)r.render=(...args)=>{for(let i=pending.length-1;i>=0;i--){const q=pending[i];if(gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE)){if(!gl.getParameter(ext.GPU_DISJOINT_EXT))__gpuSamples.push(gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q);pending.splice(i,1);}}if(!__measureFrames||pending.length>=4)return original(...args);const q=gl.createQuery();gl.beginQuery(ext.TIME_ELAPSED_EXT,q);original(...args);gl.endQuery(ext.TIME_ELAPSED_EXT);pending.push(q);};__measureFrames=true;return !!ext;})()`);
  await until('__frameSamples.length>=480');
  const timing=await ev(`(()=>{__measureFrames=false;__stopGpuProbe();const t=__frameSamples.slice(60).sort((a,b)=>a-b),g=__gpuSamples.slice(60).sort((a,b)=>a-b),c=__ob.R().labCtx(true),gl=c.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {url:location.href,tier:__ob.tier(),renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'',frames:t.length,cpuMedian:t[Math.floor(t.length*.5)],cpuP95:t[Math.floor(t.length*.95)],gpuFrames:g.length,gpuMedian:g[Math.floor(g.length*.5)],gpuP95:g[Math.floor(g.length*.95)],stats:__ob.stats(),profile:__ob.prof()};})()`);console.log('Steady frame benchmark',JSON.stringify(timing));assert.equal(logs.length,0);return;
 }
 assert.equal(info.heat.length,2);assert.ok(info.heat.every(h=>h>=0&&h<=100));
 const assets=await ev(`(async()=>{const out=[];for(const [name,a]of Object.entries(__MANIFEST.presentation)){if(name==='audio-bank.json')continue;const r=await fetch(a.url);out.push({name,status:r.status,type:r.headers.get('content-type')});}return out;})()`);console.log('Assets',JSON.stringify(assets));assert.ok(assets.every(a=>a.status===200),'local content-addressed assets serve');
 await ev(`(async()=>{const u=__MANIFEST.modules.find(m=>m.url.endsWith('/badminton/audio.js')).url;window.__qualitySound=(await import(u)).Sound;__qualitySound.resume();})()`);
 await until('!__qualitySound.debugStats().loading');let audio=await ev('__qualitySound.debugStats()');assert.equal(Object.keys(audio.decoded).length,39,'all active recordings decode');assert.equal(audio.errors.length,0);assert.equal(audio.context,'running');
 await until('__qualitySound.debugStats().active'); // The smoothed client enters match just after the newest server snapshot.
 const quiet=await ev(`(()=>{const S=__qualitySound,p=[Array(21).fill(0),Array(21).fill(0)];p[0][2]=7;p[1][2]=7;const before=S.debugStats().totalVoices;for(let i=0;i<240;i++){p[0][0]+=.1;p[1][1]-=.1;S.frame({dt:1/60,players:p,live:true});}const running=S.debugStats().totalVoices-before;const at=S.debugStats().totalVoices;S.fx.jump(false,{x:0,y:0});S.fx.jump(true,{x:0,y:0});S.fx.land(false,3,{x:0,y:0});return {looping:window.__loopedAudioSources,running,ordinaryMovement:S.debugStats().totalVoices-at};})()`);
 console.log('Quiet court regression',JSON.stringify(quiet));assert.deepEqual(quiet,{looping:0,running:0,ordinaryMovement:0},'no looping hiss, body-distance footstep clock, jump swooshes or routine landing thumps');
 if(footstepsOnly){
  await ev(`window.__stepCount=()=>Object.entries(__qualitySound.debugStats().playedSamples).filter(([n])=>n.startsWith('court_')).reduce((a,[,n])=>a+n,0);window.__keyboardBefore=__stepCount();true;`);
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,nativeVirtualKeyCode:65});await wait(1100);
  await send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,nativeVirtualKeyCode:65});await wait(250);
  const keyboard=await ev('__stepCount()-__keyboardBefore');console.log('Live keyboard footfalls',keyboard);assert.ok(keyboard>=2,'the live client connects its rendered foot plants to audio');
  // The real footwork solver and real PCM buffers, paced through four seconds of gait changes.
  await ev(`window.__stepLab=__ob.R().labCtx(true);window.__stepRows=__ob.state().p.map(p=>p.slice());__qualitySound.frame({live:false});window.__stepFrame=__qualitySound.frame;__qualitySound.frame=()=>{};window.__stepBefore=__stepCount();true;`);
  const movement=await ev(`(async()=>{const R=__ob.R(),S=__qualitySound,A=__stepLab.players,p=__stepRows;let now=performance.now(),max=0,contacts=0;const old=A.map(a=>({L:a.fw.feet.L.st,R:a.fw.feet.R.st}));for(let i=0;i<240;i++){const dt=1/60;now+=1000/60;for(let slot=0;slot<2;slot++){const row=p[slot];row[2]=(slot? -1:1)*2.3;row[3]=i<120?.8:-.8;row[0]+=row[2]*dt;row[1]+=row[3]*dt;const af=R.debugAthleteFrame(slot,row,[0,0,2,0,0,0],{live:true,match:true,strokes:[null,null],pointAt:[0,0],heat:[0,0],tick:i},dt,now);A[slot].update(af);for(const side of ['L','R']){const st=A[slot].fw.feet[side].st;if(old[slot][side]==='swing'&&st==='plant')contacts++;old[slot][side]=st;}}__stepFrame({dt,players:p,athletes:A,mySlot:0,camera:R.debugCam(),live:true});max=Math.max(max,S.debugStats().activeFootsteps);await new Promise(r=>setTimeout(r,1000/60));}return {played:__stepCount()-__stepBefore,contacts,max,takes:Object.keys(S.debugStats().playedSamples).filter(n=>n.startsWith('court_')).length};})()`);
  console.log('Rendered footfall playback',JSON.stringify(movement));assert.ok(movement.played>=8,'actual rendered footfalls play recordings (thinned: about one voiced step per 0.26 s per athlete, never two ordinary steps at once)');assert.ok(movement.played<=movement.contacts,'no extra body-travel sounds');assert.ok(movement.takes>=4,'multiple distinct takes play');assert.ok(movement.max<=3,'movement voices stay bounded');
  const paused=await ev(`(()=>{const S=__qualitySound;__stepFrame({live:false,paused:true});const n=__stepCount();for(let i=0;i<120;i++)__stepFrame({dt:1/60,players:__stepRows,athletes:__stepLab.players,live:true,paused:true});return {played:__stepCount()-n,voices:S.debugStats().activeVoices};})()`);assert.deepEqual(paused,{played:0,voices:0});
  const delivery={bankRequests:requests.filter(r=>r.url.endsWith('/audio-bank.json')).length,mediaRequests:requests.filter(r=>r.type==='Media'||/\.(mp3|wav|ogg|m4a|aac)(\?|$)/i.test(r.url)),downloads};console.log('Audio delivery',JSON.stringify(delivery));assert.equal(delivery.bankRequests,1,'one bank request across activation and all steps');assert.equal(delivery.mediaRequests.length,0,'no downloadable media URL requests');assert.equal(downloads.length,0,'no browser download events');assert.equal(logs.length,0,'no browser errors');console.log('Footsteps integration: PASS');return;
 }
 await ev(`(()=>{__qualitySound.fx.hit('smash',220,true,{x:-2,y:1,z:2});__qualitySound.fx.net({x:0,y:1,z:1});__qualitySound.fx.land(true,4,{x:-1,y:1,z:0});__qualitySound.fx.point(true,true);for(let i=0;i<50;i++)__qualitySound.fx.hit('drive',120,false,{x:1,y:-1,z:1});return 1;})()`);
 audio=await ev('__qualitySound.debugStats()');console.log('Audio',JSON.stringify(audio));assert.ok(audio.activeVoices<=audio.maxVoices,'burst respects the voice limit');assert.ok(audio.playedSamples.racket&&audio.playedSamples.rustle&&audio.playedSamples.applause);assert.equal(audio.playedSamples.step||0,0,'landings do not play the concrete footstep recording');
 await ev(`__qualitySound.toggle();__qualitySound.fx.hit('smash',200,true);true;`);assert.equal(await ev('__qualitySound.debugStats().activeVoices'),0,'mute releases voices and blocks new impacts');assert.equal(await ev('__qualitySound.muted'),true);await ev('__qualitySound.toggle()');
 await ev(`__qualitySound.frame({dt:0,players:null,live:false,paused:true})`);assert.equal(await ev('__qualitySound.debugStats().activeVoices'),0,'pause releases all transient voices');
 await shot('court-'+info.tier+'.png');
 // Hold the game renderer while inspecting physical mesh and VFX directly; no server mutation.
 await ev(`window.__qualityCtx=__ob.R().labCtx(true);window.__qualityP=__ob.R().debugPresentation();true;`);
 const net=await ev(`(()=>{const p=__qualityP,n=p.netDynamics;n.reset();n.impact({y:.6,z:1.2,vx:32,vy:5,vz:-2});for(let i=0;i<12;i++)n.step(1/120);const d=n.positions.filter((v,i)=>i%3===2),positive=Math.max(...d);p.netLook.sync();return {positive,finite:n.positions.every(Number.isFinite)};})()`);assert.ok(net.finite&&net.positive>.005,'actual net mesh responds to positive impact');
 await ev(`(()=>{for(let i=0;i<180;i++)__qualityP.heatVfx.update(1/60,[100,100],__qualityCtx.players,__qualityCtx.camera,true);__qualityCtx.renderer.render(__qualityCtx.scene,__qualityCtx.camera);return 1;})()`);await until('__qualityP.heatVfx.stats().ready');await ev('__qualityCtx.renderer.render(__qualityCtx.scene,__qualityCtx.camera)');await shot('heat-net-'+info.tier+'.png');
 assert.deepEqual(await ev('__qualityP.heatVfx.stats().tiers'),[3,3]);
 const frozenHeat=await ev('__qualityP.heatVfx.stats()');await ev('__qualityP.heatVfx.update(0,[0,0],__qualityCtx.players,__qualityCtx.camera,true)');assert.deepEqual(await ev('__qualityP.heatVfx.stats()'),frozenHeat,'paused effects retain their state');
 const fire=await ev(`(()=>{const c=__qualityCtx;let rims=0,masks=0;c.scene.traverse(o=>{if(o.userData.heatAura&&o.visible){if(o.layers.mask===1)rims++;else masks++;}});const halo=c.scene.getObjectByName('Heat aura halo');return {halo:!!halo?.visible,rims,masks,stats:__qualityP.heatVfx.stats()};})()`);console.log('Heat aura',JSON.stringify(fire));assert.ok(fire.halo&&fire.rims>0&&fire.masks>0,'on-fire athletes show the halo and rim aura');
 const detail=await ev(`(()=>{const c=__qualityCtx,p=c.players[0].root.position;window.__qualityCamera={pos:c.camera.position.toArray(),quat:c.camera.quaternion.toArray()};c.camera.position.set(p.x-3,2.2,p.z+3);c.camera.lookAt(p.x,1,p.z);__qualityP.heatVfx.update(1/60,[100,100],c.players,c.camera,true);c.renderer.render(c.scene,c.camera);return c.renderer.domElement.toDataURL('image/png').split(',')[1];})()`);fs.writeFileSync(path.join(output,'kit-fire-detail-'+info.tier+'.png'),Buffer.from(detail,'base64'));
 await ev(`__qualityCtx.camera.position.fromArray(__qualityCamera.pos);__qualityCtx.camera.quaternion.fromArray(__qualityCamera.quat);true;`);
 const bench=await ev(`(()=>{const {renderer,scene,camera,players}=__qualityCtx,p=__qualityP;const sample=active=>{p.heatVfx.reset();p.netDynamics.reset();const times=[];for(let i=0;i<170;i++){const at=performance.now();if(active){p.heatVfx.update(1/60,[100,100],players,camera,true);if(i%40===0)p.netDynamics.impact({y:0,z:1.2,vx:28,vy:1,vz:-1});p.netDynamics.step(1/60);p.netLook.sync();}renderer.render(scene,camera);if(i>=50)times.push(performance.now()-at);}times.sort((a,b)=>a-b);return {median:times[60],p95:times[114],calls:renderer.info.render.calls,triangles:renderer.info.render.triangles};};const gl=renderer.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):'',inactive:sample(false),active:sample(true)};})()`);console.log('Effect update and render submission benchmark',JSON.stringify(bench));
 await ev(`(()=>{__qualityP.heatVfx.reset();__qualityP.netDynamics.reset();__ob.R().labCtx(false);return 1;})()`);
 // Leave through the real menu and verify no heat aura survives on the home page.
 await ev(`(()=>{document.getElementById('menuBtn').click();const A=__ob.R().debugAthletes()[0];A.racket.quaternion.copy(A.racketBase).multiply(new __qualityCtx.THREE.Quaternion().setFromAxisAngle(new __qualityCtx.THREE.Vector3(0,1,0),1));A.celebrationDelay=.3;document.querySelector('[data-pane="leave"]').click();return 1;})()`);await until('location.pathname === "/badminton"');await wait(100);
 const home=await ev(`({heat:__ob.R().debugScene().heat,voices:__qualitySound.debugStats().activeVoices,neutral:__ob.R().debugAthletes().every(A=>1-Math.abs(A.racket.quaternion.dot(A.racketBase))<1e-7),clothRest:__ob.R().debugAthletes().every(A=>A.apparel.uniforms.motion.value===0)})`);assert.deepEqual(home.heat.tiers,[0,0]);assert.equal(home.voices,0);assert.ok(home.neutral&&home.clothRest,'room exit resets an interrupted flourish and garment motion');console.log('Home cleanup',JSON.stringify(home));
 await shot('home-'+info.tier+'.png');
 assert.equal(logs.length,0,'browser reports no runtime or shader errors: '+logs.join('\n'));console.log('Presentation integration: PASS; captures',output);
}catch(e){console.error(e.stack);console.error('Browser logs:',logs);if(ws){console.error('Page diagnostics:',await ev(`({url:location.href,boot:document.getElementById('boot')?.innerText,state:window.__ob?.state(),tier:window.__ob?.tier(),renderer:!!window.__ob?.R(),manifest:window.__MANIFEST?.build,body:document.body?.innerText.slice(0,500)})`).catch(x=>String(x)));await shot('failure.png').catch(()=>{});}process.exitCode=1;}
finally{
 try{if(ws)await Promise.race([send('Browser.close'),wait(1000)]);}catch{}try{if(ws)ws.close();}catch{}if(proc.exitCode===null){const ended=new Promise(r=>proc.once('exit',r));proc.kill();await ended;}
 // Verify our unique profile is a child of temp before removing it, never a normal browser profile.
 const absolute=path.resolve(profile),temp=path.resolve(os.tmpdir())+path.sep;
 if(absolute.startsWith(temp)&&path.basename(absolute).startsWith('obm-presentation-browser-')){for(let i=0;i<8;i++){try{fs.rmSync(absolute,{recursive:true,force:true});break;}catch{await wait(200);}}}
}
})();
